text="Hello there! I am wisp and I have been instructed to help guide you through The Rift.";
page=0;
boxwidth = sprite_get_width(sp_dialogue_box);
stringheight = string_height(text);
master = 0;
charcount = 0;
name = 0;
typefx1 = 0;
textnum = 0;